darwinia-network/darwinia-2.0

- runtime/crab/src/pallets/bridge_dispatch.rs
- runtime/crab/src/pallets/bridge_grandpa.rs
- runtime/crab/src/pallets/bridge_messages.rs
- runtime/crab/src/pallets/collator_selection.rs
- runtime/crab/src/pallets/evm.rs
- runtime/crab/src/pallets/fee_market.rs
- runtime/crab/src/pallets/polkadot_xcm.rs
- runtime/darwinia/src/pallets/bridge_dispatch.rs
- runtime/darwinia/src/pallets/bridge_grandpa.rs
- runtime/darwinia/src/pallets/bridge_messages.rs
- runtime/darwinia/src/pallets/evm.rs
- runtime/darwinia/src/pallets/fee_market.rs
- runtime/darwinia/src/pallets/polkadot_xcm.rs
- runtime/pangolin/src/pallets/collator_selection.rs
- runtime/pangolin/src/pallets/evm.rs
- runtime/pangolin/src/pallets/polkadot_xcm.rs
> Fix missing deps full path

- node/src/chain_spec/crab.rs
- node/src/chain_spec/darwinia.rs
- node/src/chain_spec/mod.rs
- node/src/chain_spec/pangolin.rs
- node/src/service/mod.rs
- pallet/account-migration/src/lib.rs
- pallet/account-migration/src/tests.rs
- pallet/staking/src/lib.rs
- runtime/crab/src/pallets/migrate.rs
- runtime/darwinia/src/pallets/migrate.rs
- runtime/pangolin/src/pallets/evm.rs
- runtime/pangolin/src/pallets/migrate.rs
- tool/state-processor/src/main.rs
> Some optimization

- tool/state-processor/src/system/README.md
- tool/state-processor/src/system/mod.rs
```rs
pub fn decimal_convert(main_balance: u128, remaining_balance: Option<u128>) -> U256 {
if let Some(rb) = remaining_balance {
return U256::from(main_balance)
.saturating_mul(U256::from(POW_9))
.saturating_add(U256::from(rb));
}
U256::from(main_balance).saturating_mul(U256::from(POW_9))
}
```
> Merge balance after update decimal

- pallet/staking/src/lib.rs
- pallet/staking/tests/mock.rs
- pallet/staking/tests/tests.rs
> Optimize storage

- node/src/command.rs
- node/src/service/mod.rs
Close https://github.com/darwinia-network/darwinia-2.0/issues/125
> Use correct RuntimeApi & RuntimeExecutor

- Cargo.lock
- runtime/common/Cargo.toml
- runtime/common/src/xcm_configs.rs
- runtime/crab/src/pallets/polkadot_xcm.rs
- runtime/darwinia/src/pallets/polkadot_xcm.rs
- runtime/pangolin/src/pallets/polkadot_xcm.rs
Close https://github.com/darwinia-network/darwinia-2.0/issues/131
> Convert the rest locations to H160 by hashing it

- tool/state-processor/src/adjust.rs
- tool/state-processor/src/type_registry.rs
- tool/state-processor/src/vesting/README.md
- tool/state-processor/src/vesting/mod.rs
Signed-off-by: Xavier Lau <xavier@inv.cafe>
> Fix vesting processor

- pallet/deposit/src/lib.rs
- pallet/deposit/tests/mock.rs
- pallet/deposit/tests/tests.rs
- pallet/staking/src/lib.rs
- pallet/staking/tests/mock.rs
- precompile/deposit/src/mock.rs
- precompile/staking/src/mock.rs
- runtime/crab/src/pallets/deposit.rs
- runtime/darwinia/src/pallets/deposit.rs
- runtime/pangolin/src/pallets/deposit.rs
Add APIs that @isunaslabs required.
> Improve deposit

- pallet/deposit/tests/mock.rs
- pallet/staking/src/lib.rs
- pallet/staking/tests/mock.rs
- precompile/deposit/src/lib.rs
- precompile/deposit/src/tests.rs
See https://github.com/darwinia-network/darwinia-2.0/pull/160
> Add `claim_with_penalty` interface

- tool/state-processor/src/main.rs
- tool/state-processor/src/system/mod.rs
> Handle different account types

- pallet/deposit/src/lib.rs
- pallet/staking/src/lib.rs
- pallet/staking/tests/tests.rs
> Add `restake` and fix some bugs

- precompile/staking/src/lib.rs
- precompile/staking/src/tests.rs
Related to https://github.com/darwinia-network/darwinia-2.0/pull/188
> Add `restake` interface

- Cargo.lock
- pallet/account-migration/Cargo.toml
- pallet/account-migration/src/lib.rs
- pallet/account-migration/src/tests.rs
- runtime/crab/src/pallets/account_migration.rs
- runtime/darwinia/src/pallets/account_migration.rs
- runtime/pangolin/src/pallets/account_migration.rs
> Human readable sign message

- node/src/chain_spec/crab.rs
- node/src/chain_spec/darwinia.rs
- node/src/chain_spec/pangolin.rs
- runtime/crab/src/lib.rs
- runtime/crab/src/pallets/mod.rs
- runtime/crab/src/pallets/proxy.rs
- runtime/darwinia/src/lib.rs
- runtime/darwinia/src/pallets/mod.rs
- runtime/darwinia/src/pallets/proxy.rs
- runtime/pangolin/src/lib.rs
- runtime/pangolin/src/pallets/mod.rs
- runtime/pangolin/src/pallets/proxy.rs
> Update proxy filter

- pallet/staking/src/lib.rs
- runtime/pangolin/src/lib.rs
A requirement from @isunaslabs.
> Merge collator payout

- .github/workflows/checks.yml
> Use check runtime action

- pallet/account-migration/src/lib.rs
> Add metadata for front end

- Cargo.lock
- node/Cargo.toml
- node/src/command.rs
- pallet/account-migration/Cargo.toml
- pallet/deposit/Cargo.toml
- pallet/ecdsa-authority/Cargo.toml
- pallet/message-gadget/Cargo.toml
- pallet/message-transact/Cargo.toml
- pallet/staking/Cargo.toml
- runtime/common/src/test.rs
- runtime/crab/Cargo.toml
- runtime/darwinia/Cargo.toml
- runtime/pangolin/Cargo.toml
> Fix `try-runtime`

- tool/state-processor/src/main.rs
- tool/state-processor/src/processor.rs
- tool/state-processor/src/session/mod.rs
- tool/state-processor/src/system/README.md
- tool/state-processor/src/system/mod.rs
- tool/state-processor/src/util.rs
I'll adjust the production networks' session consumer in another PR.
Due to https://github.com/paritytech/substrate/issues/13172.
> Adjust session consumer part.1

- pallet/account-migration/src/lib.rs
- pallet/deposit/src/lib.rs
- pallet/ecdsa-authority/src/lib.rs
- pallet/message-transact/src/lib.rs
- pallet/staking/src/lib.rs
> Fixes call indexes

- tool/state-processor/src/staking/README.md
- tool/state-processor/src/staking/mod.rs
- tool/state-processor/src/type_registry.rs
> Clean empty ledger

- tool/state-processor/Cargo.lock
- tool/state-processor/Cargo.toml
- tool/state-processor/src/configuration.rs
- tool/state-processor/src/system/README.md
- tool/state-processor/src/system/mod.rs
```rs
INFO  state_processor::system    > migrate special account `SiblId(2023)`
INFO  state_processor::system    > migrate special account `PalletId(da/paais)`
INFO  state_processor::system    > migrate special account `SiblId(2004)`
INFO  state_processor::system    > migrate special account `PalletId(PotStake)`
INFO  state_processor::system    > migrate special account `PalletId(da/ethrl)`
INFO  state_processor::system    > migrate special account `PalletId(da/trsry)`
INFO  state_processor::system    > migrate special account `PalletId(da/crais)`
INFO  state_processor::system    > migrate special account `PalletId(da/ethfe)`
INFO  state_processor::system    > migrate special account `PalletId(py/trsry)`
INFO  state_processor::system    > migrate special account `PalletId(da/staki)`
INFO …
```
> Handle special accounts

- Cargo.lock
- pallet/account-migration/Cargo.toml
- pallet/account-migration/src/lib.rs
- pallet/account-migration/tests/mock.rs
- pallet/account-migration/tests/tests.rs
- runtime/crab/src/pallets/deposit.rs
- runtime/crab/src/pallets/system.rs
- runtime/darwinia/src/pallets/deposit.rs
- runtime/darwinia/src/pallets/system.rs
- runtime/pangolin/src/pallets/deposit.rs
- runtime/pangolin/src/pallets/system.rs
> Migrate multisig

- .github/workflows/checks.yml
- .github/workflows/staging.yml
- node/Cargo.toml
- node/src/chain_spec/mod.rs
- node/src/command.rs
- node/src/service/executors.rs
- node/src/service/mod.rs
- runtime/crab/src/lib.rs
- runtime/crab/src/pallets/aura.rs
- runtime/darwinia/src/lib.rs
- runtime/darwinia/src/pallets/aura.rs
- runtime/pangolin/src/lib.rs
- runtime/pangolin/src/pallets/aura.rs
- tool/state-processor/src/system/mod.rs
> Manage runtime through features

- tool/state-processor/src/main.rs
- tool/state-processor/src/parachain_system/README.md
- tool/state-processor/src/parachain_system/mod.rs
- tool/state-processor/src/processor.rs
> Process parachain system

- Cargo.lock
- Cargo.toml
Please check this commit: https://github.com/paritytech/cumulus/compare/polkadot-v0.9.37...darwinia-network:cumulus:remove-assertion-v0.9.37
> Remove assertions in HRMP&DMP

- Cargo.lock
- node/Cargo.toml
- node/src/chain_spec/mod.rs
- node/src/chain_spec/pangolin.rs
- node/src/command.rs
> Auto load large genesis

- .github/release-template.md
- .github/workflows/checks.yml
- .github/workflows/release.yml
Preview
https://github.com/darwinia-network/darwinia-2.0/actions/runs/4329683001/jobs/7561105215#step:11:1
> Add Release CI
